# environment.yml
name: caaf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - setuptools
  - wheel
  - pyyaml
  - requests
  - aiohttp
  - pytest
  - black
  - flake8
  - mypy
  - pip:
    - anthropic  # Claude API client
    - ollama     # Ollama Python client
